package cellar

import (
	"crypto/rand"
	"fmt"
	"io"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func genRandBytes(size int) []byte {

	key := make([]byte, size)
	var err error
	if _, err = io.ReadFull(rand.Reader, key); err != nil {
		panic(err)
	}
	return key
}

func genSeedBytes(size int, seed int) []byte {
	buf := make([]byte, size)
	for i := 0; i < size; i++ {
		buf[i] = byte((i + seed) % 256)
	}
	return buf
}
func checkSeedBytes(data []byte, seed int) error {
	for i := 0; i < len(data); i++ {
		expect := byte((i + seed) % 256)
		if data[i] != expect {
			return fmt.Errorf("Given seed %d expected %d at position %d but got %d", seed, expect, i, data[i])
		}
	}
	return nil
}

func newCompressor() Compressor {
	return &ChainCompressor{CompressionLevel: 10}
}

func newDecompressor() Decompressor {
	return &ChainDecompressor{}
}

var key = genRandBytes(16)

func newCipher() Cipher {
	return NewAES(key)
}

func TestWriter_Append_Read(t *testing.T) {
	db, err := New(dbDir, WithNoFileLock, WithMetaDB(newBoltMetaDB()))
	require.NoError(t, err)

	tcs := []struct {
		input string
	}{
		{
			"small string",
		},
		{
			"larger string with some fluff",
		},
		{
			"fairly large string with some fluff and other stuff to see if we can write large things",
		},
	}

	for _, tc := range tcs {
		_, err := db.Append([]byte(tc.input))
		require.NoError(t, err)

	}
	db.Flush()

	reader := db.Reader()
	for _, tc := range tcs {
		found := false
		err = reader.Scan(func(pos *ReaderInfo, data []byte) error {
			if string(data) == tc.input {
				found = true
			}
			return nil
		})
		time.Sleep(1 * time.Second)
		require.NoError(t, err)
		assert.True(t, found)
	}
}

func BenchmarkWriter_Append_Small(b *testing.B) {
	const (
		Message = "a fairly small message"
	)
	db, err := New(dbDir, WithNoFileLock, WithMetaDB(newBoltMetaDB()))
	require.NoError(b, err)

	for i := 0; i < b.N; i++ {
		_, err = db.Append([]byte(Message))
		require.NoError(b, err)
	}
}

func BenchmarkWriter_Append_Medium(b *testing.B) {
	const (
		Message = "a medium sized message, this one is approximately three times as long."
	)
	db, err := New(dbDir, WithNoFileLock, WithMetaDB(newBoltMetaDB()))
	require.NoError(b, err)

	for i := 0; i < b.N; i++ {
		_, err = db.Append([]byte(Message))
		require.NoError(b, err)
	}
}

func BenchmarkWriter_Append_Large(b *testing.B) {
	const (
		Message = "a large sized message, this one is approximately 9 times as long as the smaller message, and 3 times as long" +
			"as the medium message. I wonder how these are autogenerated? I bet it is an AI powered by AR."
	)
	db, err := New(dbDir, WithNoFileLock, WithMetaDB(newBoltMetaDB()))
	require.NoError(b, err)

	for i := 0; i < b.N; i++ {
		_, err = db.Append([]byte(Message))
		require.NoError(b, err)
	}
}
