apiVersion: batch/v1
kind: Job
metadata:
  name: cellardb-e2e
spec:
  completions: 2
  parallelism: 2
    spec:
      containers:
      - name: c
        image: gcr.io/<project>/job-wq-1
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure